jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Define Variables
        id: defs
        run:
          echo "MY_VARIABLE=value" >> $GITHUB_ENV

      - name: Set New Variable Based on Existing Variable
        env:
          MY_SUB_VARIABLE: ${{ env.MY_VARIABLE + '_suffix' }}
        run: echo "MY_SUB_VARIABLE=${{ env.MY_SUB_VARIABLE }}"
